### ISSUE TITLE
Add fixes to BeebEm release?

### ISSUE THREAD

**Issue by chrisn** [mmbeeb/STEST#1]
I've been working on the BeebEm serial port emulation (see https://github.com/stardot/beebem-windows/issues/117 for the details), and the fixes you made here seem to resolve that user's issue. Do you mind if I include your fixes into the next version of BeebEm?

**Comment by mmbeeb** [comment]
Happy for these fixes to be included.  I did them because I wanted to use BeebEm to develop something or other, but found it didn't work.
mm

**Comment by chrisn** [comment]
Thank you! I'll keep working on it...
